# for Watermill development purposes.
# For Watermill based application docker please check https://watermill.io/docs/getting-started/
---
services:
  kafka-1:
    image: redpandadata/redpanda:v26.1.7
    restart: unless-stopped
    logging:
      driver: none
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://kafka-1:9092,external://localhost:19092
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr kafka-1:33145
      - --seeds kafka-1:33145,kafka-2:33145,kafka-3:33145
      - --mode dev-container
      - --smp 1
      - --memory 1500M
      - --default-log-level=warn
      - --set redpanda.topic_partitions_per_shard=10000
      - --set redpanda.topic_memory_per_partition=51200
      - --set redpanda.log_segment_size=1048576
    volumes:
      - kafka-1-data:/var/lib/redpanda/data
    ports:
      - 19092:19092

  kafka-2:
    image: redpandadata/redpanda:v26.1.7
    restart: unless-stopped
    logging:
      driver: none
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19093
      - --advertise-kafka-addr internal://kafka-2:9092,external://localhost:19093
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr kafka-2:33145
      - --seeds kafka-1:33145,kafka-2:33145,kafka-3:33145
      - --mode dev-container
      - --smp 1
      - --memory 1500M
      - --default-log-level=warn
      - --set redpanda.topic_partitions_per_shard=10000
      - --set redpanda.topic_memory_per_partition=51200
      - --set redpanda.log_segment_size=1048576
    volumes:
      - kafka-2-data:/var/lib/redpanda/data
    ports:
      - 19093:19093

  kafka-3:
    image: redpandadata/redpanda:v26.1.7
    restart: unless-stopped
    logging:
      driver: none
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19094
      - --advertise-kafka-addr internal://kafka-3:9092,external://localhost:19094
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr kafka-3:33145
      - --seeds kafka-1:33145,kafka-2:33145,kafka-3:33145
      - --mode dev-container
      - --smp 1
      - --memory 1500M
      - --default-log-level=warn
      - --set redpanda.topic_partitions_per_shard=10000
      - --set redpanda.topic_memory_per_partition=51200
      - --set redpanda.log_segment_size=1048576
    volumes:
      - kafka-3-data:/var/lib/redpanda/data
    ports:
      - 19094:19094

  kafka-ui:
    image: "provectuslabs/kafka-ui:latest"
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-1:9092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

volumes:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:
